### ISSUE TITLE
类型出错？？？？

### ISSUE THREAD

**Issue by lypingk** [SpaceLearner/SessionRec-pytorch#1]
请问大家有出现这个问题吗？
dgl._ffi.base.DGLError: Expect all graphs to have the same schema on nodes["s2"].data, but graph 1 got
	{'iid': Scheme(shape=(2,), dtype=torch.int32), 'last': Scheme(shape=(), dtype=torch.int32)}
which is different from
	{'iid': Scheme(shape=(2,), dtype=torch.int64), 'last': Scheme(shape=(), dtype=torch.int32)}.

**Comment by better46** [comment]
Yes,I have also meet this question.
![image](https://user-images.githubusercontent.com/56395712/157291434-263f973e-2728-4a57-ae10-2d05f9e74ea7.png)

**Comment by SpaceLearner** [comment]
I haven't met this issue, could you please check whether the environment aligns with the recommended environment?

**Comment by better46** [comment]
Yes,thanks.I find the version of dgl is different with yours.
