### ISSUE TITLE
I cannot reproduce the performance of the model in the paper

### ISSUE THREAD

**Issue by Nishikata97** [SpaceLearner/SessionRec-pytorch#3]
First I used **environment.yaml** to configure the environment and **start.sh** to test on the **diginetica** dataset, here are the results for the last four epochs:
 20%|██        | 6/30 [14:52<59:37, 149.08s/it]  Epoch 5: MRR = 19.008%, Hit = 55.406%
Batch 8500: Loss = 4.0826, Time Elapsed = 21.61s
Batch 8600: Loss = 4.0721, Time Elapsed = 9.60s
Batch 8700: Loss = 4.0687, Time Elapsed = 9.53s
Batch 8800: Loss = 4.0753, Time Elapsed = 9.51s
Batch 8900: Loss = 4.0801, Time Elapsed = 10.03s
Batch 9000: Loss = 4.0732, Time Elapsed = 9.77s
Batch 9100: Loss = 4.0731, Time Elapsed = 9.63s
Batch 9200: Loss = 4.0772, Time Elapsed = 9.47s
Batch 9300: Loss = 4.0917, Time Elapsed = 10.03s
Batch 9400: Loss = 4.0949, Time Elapsed = 9.88s
Batch 9500: Loss = 4.0945, Time Elapsed = 9.58s
Batch 9600: Loss = 4.0916, Time Elapsed = 9.70s
Batch 9700: Loss = 4.0954, Time Elapsed = 9.76s
Batch 9800: Loss = 4.1006, Time Elapsed = 9.96s
 23%|██▎       | 7/30 [17:21<57:01, 148.75s/it]Epoch 6: MRR = 19.013%, Hit = 55.383%
Batch 9900: Loss = 4.0622, Time Elapsed = 21.49s
Batch 10000: Loss = 4.0686, Time Elapsed = 9.53s
Batch 10100: Loss = 4.0630, Time Elapsed = 9.81s
Batch 10200: Loss = 4.0753, Time Elapsed = 9.31s
Batch 10300: Loss = 4.0691, Time Elapsed = 9.69s
Batch 10400: Loss = 4.0818, Time Elapsed = 9.66s
Batch 10500: Loss = 4.0660, Time Elapsed = 9.58s
Batch 10600: Loss = 4.0944, Time Elapsed = 9.87s
Batch 10700: Loss = 4.0769, Time Elapsed = 9.77s
Batch 10800: Loss = 4.0792, Time Elapsed = 9.62s
Batch 10900: Loss = 4.0737, Time Elapsed = 9.85s
Batch 11000: Loss = 4.0862, Time Elapsed = 9.36s
Batch 11100: Loss = 4.0784, Time Elapsed = 9.50s
Batch 11200: Loss = 4.0959, Time Elapsed = 10.21s
Epoch 7: MRR = 19.006%, Hit = 55.379%
 27%|██▋       | 8/30 [19:48<54:23, 148.35s/it]Batch 11300: Loss = 4.0781, Time Elapsed = 21.73s
Batch 11400: Loss = 4.0772, Time Elapsed = 9.75s
Batch 11500: Loss = 4.0463, Time Elapsed = 9.50s
Batch 11600: Loss = 4.0733, Time Elapsed = 9.85s
Batch 11700: Loss = 4.0664, Time Elapsed = 9.95s
Batch 11800: Loss = 4.0548, Time Elapsed = 9.84s
Batch 11900: Loss = 4.0820, Time Elapsed = 9.80s
Batch 12000: Loss = 4.0775, Time Elapsed = 9.51s
Batch 12100: Loss = 4.0711, Time Elapsed = 9.55s
Batch 12200: Loss = 4.0749, Time Elapsed = 9.63s
Batch 12300: Loss = 4.0626, Time Elapsed = 9.86s
Batch 12400: Loss = 4.0845, Time Elapsed = 9.82s
Batch 12500: Loss = 4.0734, Time Elapsed = 9.45s
Batch 12600: Loss = 4.0856, Time Elapsed = 9.66s
 27%|██▋       | 8/30 [22:16<1:01:14, 167.02s/it]
Epoch 8: MRR = 19.006%, Hit = 55.379%
MRR@20	HR@20
19.015%	55.406%

Process finished with exit code 0

**Comment by SpaceLearner** [comment]
You can try first clone the repo again and add "--extra" and "--fusion" on the command line of start.sh and increase the order to get better performance.
