### ISSUE TITLE
Is the processing code related to yoochoose missing？

### ISSUE THREAD

**Issue by lazyloafer** [SpaceLearner/SessionRec-pytorch#5]

**Comment by lazyloafer** [comment]
Meanwhile, I convert yoochoose1/64 in the SRGNN source code to the required format (the training data in SRGNN is [[train_session_1, train_session_2,... Train_session_n], [target_1, target_2,... target_n,]], and I combine each target into the end of the corresponding train_session. The logic may be no problem). I train yoochoose1/64 with this source code (granularity level=3, --extra, --fusion), MRR can only reach the level of srgnn (70%), according to the ablation experiment in this paper, it should reach 72%
![企业微信截图_16548259754838](https://user-images.githubusercontent.com/48559992/172978258-87971d79-e275-413b-87ed-b285f6b5ee43.png)
![82faef3823278d6710b09c9f1f6fab7](https://user-images.githubusercontent.com/48559992/172978297-ad929041-8e67-4a53-9171-5bc26969e4b2.png)

**Comment by SpaceLearner** [comment]
You can directly transform youchoose1/64 from SR-GNN without extra augmentations.
